-- if GetLocale() =="zhCN" then
	-- QUICK_LOOT_ENABLE = "允许快速拾取物品";
	-- QUICK_LOOT_AUTOHIDE = "当没有物品时自动隐藏面板"
-- elseif GetLocale() == "zhTW" then
	-- QUICK_LOOT_ENABLE = "允許快速拾取物品";
	-- QUICK_LOOT_AUTOHIDE = "當沒有物品時自動隱藏面板"
-- end
-- -------------------注册插件类型-----------------------------------
-- --------------参数1 插件的名字-----------------------------------
-- --------------参数2 插件的类型。-----------------------------------
-- --------------参数3 启动插件是否需要重载界面。默认nil 可设置为true-----------------------------------
-- BFNew_RegisterAddon("QuickLoot",{BFNew_AddonTypeTable[7],BFNew_AddonTypeTable[10]},nil,nil,true)
-- --------------------------------------------------------------
-- --------------------------------------------------------------
-- -------------------注册插件互斥信息-------------------------------------------
-- -------------------参数1 互斥的插件名字列表的Tab-------------------------------------------
-- -- BFNew_RegisterAddonexclusiveTab({"Skada","Recount"})
-- --------------------注册插件配置信息----------------------------------
-- --------------参数1 插件的名字-----------------------------------
-- --------------参数2 配置的类型。-----------------------------------
-- --------------参数3 配置名字-----------------------------------
-- --------------参数4 配置显示的名字-----------------------------------
-- --------------参数5 配置的鼠标提示-----------------------------------
-- --------------参数6 （Checkbox）配置的默认值  ----  true false 不要为nil-----------------------------------
-- --------------参数7 （Checkbox）配置的CallBack函数  2个参数 第一个为 toggle_value  为 true or false  后一个为是否初始化的标识-----------------------------------
-- --------------参数8 配置的层级 默认0-----------------------------------
-- BFNew_RegisterAddonConfig("QuickLoot","CheckBox","EnableQuickLoot",QUICK_LOOT_ENABLE,nil,
-- true,-----默认值
	-- function (arg)
		-- if (arg  and not __QuickLoot_Enable) then
			-- __QuickLoot_Enable = 1;	
			-- -- if (not isHooked) then
				-- -- LootFrame:HookScript("OnEvent", __QuickLoot_LootFrame_OnEvent);
-- --					LootFrame:HookScript("Update", __QuickLoot_LootFrame_Update);
				-- -- hooksecurefunc("LootButton_OnClick", __QuickLoot_LootButton_OnClick);
				-- -- isHooked = true;
			-- -- end
		-- elseif (arg == false and __QuickLoot_Enable) then
			-- __QuickLoot_Enable = nil;				
		-- end
	-- end
-- )
-- BFNew_RegisterAddonConfig("QuickLoot","CheckBox","QuickLootAutoHide",QUICK_LOOT_AUTOHIDE,nil,
-- false,-----默认值
	-- function (__arg)
		-- if __arg  then
			-- __QuickLoot_AutoHide = 1;
		-- else
			-- __QuickLoot_AutoHide = nil;
		-- end
	-- end,1
-- )